import { createSlice } from "@reduxjs/toolkit"
import anecdoteService from "../services/anecdotes"
// id is auto-generated by json-server
// const getId = () => (100000 * Math.random()).toFixed(0)

/*This function returns an object containing the reducer and the action creators defined by the reducers parameter */
const anecdoteSlice = createSlice({
  name:'anecdote', 
  initialState: [],
  reducers: {
    voteAnecdote(state, action) {
      const id = action.payload
      // find the anecdote by id
      const anecdoteToChange = state.find(anecdote => anecdote.id === id)
      // create a new anecdote by incrementing vote number
      const changedAnecdote = {...anecdoteToChange, votes:anecdoteToChange.votes + 1}
      // return a new state with new anecdote in place
      return state
      .map(anecdote => anecdote.id === changedAnecdote.id ? changedAnecdote : anecdote)
      .sort((anecdote1, anecdote2) => anecdote2.votes - anecdote1.votes)
    },
  
    addNewAnecdote(state, action) {
      console.log("Action ", action);
      console.log(JSON.parse(JSON.stringify(state)));
      return state.concat(action.payload)
    }, 
    
    setAnecdotes(state, action) {
      return action.payload
    }
  }

})


export const {voteAnecdote, addNewAnecdote, setAnecdotes} = anecdoteSlice.actions

//React Thunk pattern receives Redux dispatch and getState methods as parameters.
// Use this to have a dispatcher accessible in other non-component place.
export const initializeAnecdotes = () => {
  return async dispatch => {
    const anecdotes = await anecdoteService.getAll()
    dispatch(setAnecdotes(anecdotes))
  }
}

//React Thunk pattern receives Redux dispatch and getState methods as parameters.
// Use this to have a dispatcher accessible in other non-component place.
export const addAnecdote = (newAnecdote) => {
  return async dispatch => {
    const anecdote = await anecdoteService.addAnecdote(newAnecdote)
    dispatch(addNewAnecdote(anecdote))
  }
}
export default anecdoteSlice.reducer